ActionCable
IljaBekirov/stackoverflow pull request #11
Opened 2021-03-11 23:31 UTC by IljaBekirov

2021-03-17 09:28 UTC, vkurennov requested changes

2021-03-17 09:28 UTC, vkurennov commented on app/channels/comments_channel.rb
> +    stream_from "comments"
так у тебя будет стрим для вообще всех комментов к любым вопросам и ответам и даже если ты на клиенте фильтруешь их, то все равно в фоне будет идти большой поток данных, что будет замедлять работу всего приложения у пользователя. поэтому здесь, как и в ответах, стоит разделить по question_id стримы

2021-03-17 09:28 UTC, vkurennov commented on app/controllers/concerns/commented.rb
> +module Commented
комментарии вполне самостоятельный ресурс и их лучше сделать отдельным контроллером, не нужно все по консернам раскидывать, а то так можно дойти до того, что и ответы вынести в консерн и включить в контроллер вопросов. если у тебя есть сущность и у нее основные операции укладываются в CRUD, то скорее всего, это отдельный ресурс.

2021-03-17 23:41 UTC, IljaBekirov commented on app/channels/comments_channel.rb
> +    stream_from "comments"
Поправил

2021-03-17 23:41 UTC, IljaBekirov commented on app/controllers/concerns/commented.rb
> +module Commented
Поправил

2021-03-18 06:54 UTC, vkurennov approved these changes

2021-03-18 21:33 UTC, merged