6 acc tests
IljaBekirov/stackoverflow pull request #6
Opened 2021-01-30 01:15 UTC by IljaBekirov

2021-01-30 12:21 UTC, IvanShamatov requested changes

2021-01-30 12:21 UTC, IvanShamatov commented on app/controllers/questions_controller.rb
> +    if @question.update(question_params)
здесь тоже нужна проверка на авторство

2021-01-30 12:21 UTC, IvanShamatov commented on spec/controllers/questions_controller_spec.rb
> +
нет проверки сценария, когда это пытается сделать не автор, вот и забыл поэтому

2021-01-30 12:21 UTC, IvanShamatov commented on spec/controllers/questions_controller_spec.rb
> +      expect(response).to redirect_to questions_path
здесь тоже не хватает этой проверки

2021-01-30 12:21 UTC, IvanShamatov commented on spec/features/answer/delete_spec.rb
> +require 'rails_helper'
на update нет спеки

2021-01-31 00:57 UTC, IljaBekirov commented on spec/features/answer/delete_spec.rb
> +require 'rails_helper'
@IvanShamatov , по update вроде в задании не было. Но я доделал.

2021-01-31 10:48 UTC, IvanShamatov approved these changes

2021-02-02 17:19 UTC, merged